#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: nbscuid default book
author: none
copyright: '2023'

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off
  only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: nbscuid-default.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

sphinx:
  config:
    #bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Information about where the book exists on the web
# repository:
#   url: https://github.com/rmshkv/nbscuid
#   path_to_book: notebooks
#   branch: main

launch_buttons:
  jupyterhub_url: 'https://jupyterhub.hpc.ucar.edu'
  notebook_interface: 'jupyterlab'

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
#  favicon: favicon.ico
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: false
  #google_analytics_id: UA-196809533-2

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    - smartquotes
    - substitution
    # - tasklist
